OBJECTS = mp1_20150038.o
EXEC = mp1_20150038
FLAGS = -Wall
CC = g++

$(EXEC):$(OBJECTS)
	$(CC) $(FLAGS) -o $(EXEC) mp1_20150038.cpp

clean: 
	rm -f mp1_20150038 mp1_20150038.o make_input a.out make_input.o result_*
